# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Svix < Formula
  desc "Svix CLI utility"
  homepage "https://www.svix.com"
  version "0.18.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/svix/svix-cli/releases/download/v0.18.2/svix_0.18.2_Darwin_x86_64.tar.gz"
      sha256 "56d289c6daf49199af98fab6e06237c60b1e0ce695d147a160ecb3cf02241fd1"

      def install
        bin.install "svix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/svix/svix-cli/releases/download/v0.18.2/svix_0.18.2_Darwin_arm64.tar.gz"
      sha256 "b831f5916659a1892666bd39bc8a5188cd761754972c43297f5d228febbb9e92"

      def install
        bin.install "svix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/svix/svix-cli/releases/download/v0.18.2/svix_0.18.2_Linux_x86_64.tar.gz"
      sha256 "651bd34d4580f26bd696c3adca70c24e88a5795e46c0373abf909e8c8c9c18a2"

      def install
        bin.install "svix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/svix/svix-cli/releases/download/v0.18.2/svix_0.18.2_Linux_arm64.tar.gz"
      sha256 "9821bc1e36a86f39e03a613ef9f29ae0d255b59e243d46f582c8e49a4eba4503"

      def install
        bin.install "svix"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing the Svix CLI! If this is your first time using the CLI, checkout our docs at https://docs.svix.com.
    EOS
  end
end
