# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Svix < Formula
  desc "Svix CLI utility"
  homepage "https://www.svix.com"
  version "0.18.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/svix/svix-cli/releases/download/v0.18.3/svix_0.18.3_Darwin_arm64.tar.gz"
      sha256 "2f2ee9b539050596ad24deef627a0e23af4f05367401079a23707d467003eb40"

      def install
        bin.install "svix"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/svix/svix-cli/releases/download/v0.18.3/svix_0.18.3_Darwin_x86_64.tar.gz"
      sha256 "c876a3a32048099c8e9153eaa95e4bb8f28a86f39901baff5a259f9298299605"

      def install
        bin.install "svix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/svix/svix-cli/releases/download/v0.18.3/svix_0.18.3_Linux_x86_64.tar.gz"
      sha256 "10719775eba4326b8f26e4f0a4cf9f712840cc0ac97a9f45bcd2cb5ff526f321"

      def install
        bin.install "svix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/svix/svix-cli/releases/download/v0.18.3/svix_0.18.3_Linux_arm64.tar.gz"
      sha256 "1a800aaf6b672551a229cb7c724344e5069302fa97dfeb0b716c7120b4878bba"

      def install
        bin.install "svix"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing the Svix CLI! If this is your first time using the CLI, checkout our docs at https://docs.svix.com.
    EOS
  end
end
