# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Svix < Formula
  desc "Svix CLI utility"
  homepage "https://www.svix.com"
  version "0.10.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/svix/svix-cli/releases/download/v0.10.0/svix_0.10.0_Darwin_x86_64.tar.gz"
      sha256 "b8cf1a1478bec7a943f4133a2779bae704b2647d73797f6e59cb652d23e10907"
    end
    if Hardware::CPU.arm?
      url "https://github.com/svix/svix-cli/releases/download/v0.10.0/svix_0.10.0_Darwin_arm64.tar.gz"
      sha256 "67492a153b8e8b84b3b55b923bcb4e3402e0fda4340aa9e0982fe1072c7a4f59"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/svix/svix-cli/releases/download/v0.10.0/svix_0.10.0_Linux_x86_64.tar.gz"
      sha256 "3dff49aa975b95835b5f24ad3675f155514b38bc477fa2e1c6e77c1bcdf154f2"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/svix/svix-cli/releases/download/v0.10.0/svix_0.10.0_Linux_arm64.tar.gz"
      sha256 "33ae9cc44f751152828c067c190be4ac93dd99324ee6ff80dcc5a2d160319ff4"
    end
  end

  def install
    bin.install "svix"
  end

  def caveats; <<~EOS
    Thanks for installing the Svix CLI! If this is your first time using the CLI, checkout our docs at https://docs.svix.com.
  EOS
  end
end
